# Stage 1: Build react app
FROM node:20.12.1 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Serve react app using NGINX
FROM nginx:latest
# Install envsubst
RUN apt-get update && apt-get install -y gettext-base
# Copy your NGINX configuration file
COPY nginx.conf.template /etc/nginx/nginx.conf.template 

# Copy your frontend build files
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"