name: Publish Docker image 

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push Docker image for backend
        uses: docker/build-push-action@v3
        with:
          context: backend/
          push: true
          tags: manjunath728/demo-backend:latest
      - name: Build and push Docker image for frontend
        uses: docker/build-push-action@v3
        with:
          context: frontend/
          push: true
          tags: manjunath728/demo-frontend:latest