name: Publish Docker image 

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Generate unique tag
        id: tag
        run: echo "::set-output name=TAG::$(date +%Y%m%d%H%M%S)"
      
      - name: Build and push Docker image for backend
        uses: docker/build-push-action@v3
        with:
          context: backend/
          push: true
          tags: manjunath728/demo-backend:${{ steps.tag.outputs.TAG }}
      
      - name: Build and push Docker image for frontend
        uses: docker/build-push-action@v3
        with:
          context: frontend/
          push: true
          tags: manjunath728/demo-frontend:${{ steps.tag.outputs.TAG }}

      - name: Update Helm chart values
        run: |
          sed -i 's/\(tag:\s*\)[0-9]*/\1${{ steps.tag.outputs.TAG }}/' cicd/values.yaml
        working-directory: ./CICD/

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Automated update of Helm chart values"
          git push
